### ISSUE TITLE
org-jira-get-issues locking up Emacs

### ISSUE THREAD

**Issue by Lownin** [ahungry/org-jira#275]
Every time I invoke org-jira-get-issues, Emacs locks up.  It used to work for me, and runs a CPU core at 100%.  headlines-only seems to work okay.  I'm a bit of an Emacs newbie, and not clear on how to troubleshoot it.

**Comment by rand-fu** [comment]
This also seems to be happening for me in the last week or so. I think after bumping my org version but am not 100% sure if that's the cause.  I can seemingly do everything except fetch issues from a board `org-jira-get-issues-by-board` and get issues `org-jira-get-issues`. Fetching just the head or single issues works fine though. I added request.el logging to my config...

```
(setq request-log-level 'blather)
(setq request-message-level 'blather)
```

...the problem is the entire emacs session locks up and I can't `C-g` interrupt so I end up having to kill the entire session and lose the message buffer before I can see what if anything is happening.

**Comment by Lownin** [comment]
@rand-fu confirmed, I am also having the problem with org-jira-get-issues-by-board and can't C-g interrupt.

**Comment by rand-fu** [comment]
I was able to debug this a little further by running a `kill -SIGUSR2` on my stuck emacs process id.

- Run `org-jira-get-issues-by-board`  and emacs locks up as expected.
- Attempt to `C-g` interrupt to no avail.
- `kill -SIGUSR2 <emacs session PID>`

At this point my emacs session returned and I was able to see what's in the message buffer. Nothing looks abnormal and the board sync'ed... if I attempt to run `org-jira-get-issues-by-board` again it works as expected and I cannot recreate the issue. I can even run `org-jira-get-issues` and it works too.

This makes me wonder if emacs is doing some processing in the background or copying data in memory maybe? I'm not sure what it is doing that causes the lock up though. When I have more time I'll give my output a closer look.

cc @Lownin in case it helps you find anything on your end.

**Comment by ahungry** [comment]
If you suspect it may be org related - could you supply the output of "M-x org-version", and then (if able) try to reproduce on an older org version?  I'm on 9.4.4 at the moment.

There hasn't been a significant org-jira patch or update for 2+ months (about a week ago I adjusted some option in a defcustom, but that should not be relevant here).

**Comment by ahungry** [comment]
It's org 9.5 related - I was on 9.4.4 that ships with my Emacs, I updated to 9.5 from the GNU Elpa repository, and the issue occurs.

In my case, my Emacs did not freeze, but "top" showed 5 Emacs processes running at 100% CPU each.

Org Jira does have heavy usage of async calls to render.

My guess is either org broke something we use, or slightly changed the behavior (perhaps causing an infinite loop in one of the rendering functions).

Does someone have a link to the Org source?

If it isn't too much, I can peek at what changed between 9.4.4 and 9.5, but if it's a massive amount, we may need someone on the Org side to weigh in.

**Comment by ahungry** [comment]
In the meantime, I'd recommend `M-x package-delete org-9.5`, and stick to the one shipped with Emacs.

**Comment by ahungry** [comment]
Just a hunch - maybe related to this breaking change:

"
org-goto-first-child now works before first heading

When point is before first heading org-goto-first-child will move point to the first child heading, or return nil if no heading exist in buffer. This is in line with the fact that everything before first heading is regarded as outline level 0, i.e. the parent level of all headings in the buffer.

Previously org-goto-first-child would do nothing before first heading, except return nil.
"

https://orgmode.org/Changes.html

Of course, the code that relies on it in org-jira has been present for just shy of 10 years...

I'm going to overwrite the org-9.5 definition of this function with the 9.4.4 locally if I can, and see if the issue in org-jira persists.  If not, we know this is the problem function.

**Comment by ahungry** [comment]
Ok, it turns out I can't reproduce it (given that I tied my high cpu usage to async-comp stuff).

If your org file is structured in a way where it is hitting a problem with org-goto-first-child, you may be able to diagnose it by doing what I was attempting (overwriting the new def with the old):

```elisp
(defun org-goto-first-child ()
  "Goto the first child, even if it is invisible.
Return t when a child was found.  Otherwise don't move point and
return nil."
  (let (level (pos (point)) (re org-outline-regexp-bol))
    (when (ignore-errors (org-back-to-heading t))
      (setq level (outline-level))
      (forward-char 1)
      (if (and (re-search-forward re nil t) (> (outline-level) level))
	        (progn (goto-char (match-beginning 0)) t)
	      (goto-char pos) nil))))
```

Eval that, and see if the issues fail to fetch, or if things proceed as they did before (also, please try org 9.4.4 vs 9.5 to help pinpoint org, or some other lib).

**Comment by rand-fu** [comment]
@ahungry thank for the follow up! I didn't expect that would be an issue in org 9.5 but that's my own ignorance. Also interesting you were unable to reproduce but I finally got a little time to test more on my end.

Since you couldn't reproduce,  seems like a good guess I'm hitting a problem with `org-goto-first-child`. First I tested several different jira boards to see if the behavior is consistent and it seems to be. With the request.el logging still set to `blather` it looks like its getting hung up on the rendering issues step.

If I eval the function above it looks like things sync again without issue. All boards that I tested and were impacted before sync fine now.  I need to do a little more testing with other functions but so far so good. I considered playing around with the structure of those org files once they initially sync and see if there's any change if I remove the old def in favor of the new. No revelations there yet.

Also working on testing downgrading to org 9.4.6 but I think Im running into a dependency issue in doom emacs that I'm debugging for downgrading the org version. I'll report back when I can test that but looks like you may have found the culprit.

**Comment by rand-fu** [comment]
Well I may have spoken too soon... Even if I eval and keep that redefined function in my config the behavior returns... sometimes it works and sometimes it doesn't... if it syncs one board correctly it seems like it will sync all of them without issue, but Im not clear on what the problem is now and why the issue mostly persists.

**Comment by ezmiller** [comment]
I'm also experiencing this on org v9.3. I haven't had a chance to debug yet, and I'm not great at debugging emacs. But I will see if I can carve out some time.

**Comment by madsroskar** [comment]
I'm also experiencing the same, org v9.6. I can't yet tell if it's the same reason, but the best I've managed to narrow it down is that an issue with an image attachment makes emacs freeze up. I'll try to debug it a bit later today and see if I can figure out what's going on.

I've also gotten stuck with `org-jira-update-worklogs-for-issue` being the last message in the messages buffer when trying to fetch all issues, but in this case, I've been fetching issues one by one to find any that fail

**Comment by hansffu** [comment]
I did some debugging and managed to get it working by setting `org-element-use-cache` to `nil`.
Backtrace was 
```
  org-element--cache-sync(...)
  org-element-at-point()
  org-jira--is-top-headline\\?(...)
  org-jira--maybe-render-top-heading(...)
  org-jira--render-issue(...)
  org-jira--render-issues-from-issue-list(...)
  org-jira-get-issues(...)
```

**Comment by ahungry** [comment]
If it might be image related - is everyone in thread using GUI Emacs?  I'm always on non-GUI myself.

**Comment by madsroskar** [comment]
I'm on GUI emacs

* `GNU Emacs 27.2 (build 1, aarch64-apple-darwin20.6.0, Carbon Version 164 AppKit 2022.6) of 2021-09-13`
* MacOS 11.5.1

No clue if the specifics matter at all, but adding it for good measure. I'll try to find a way to get some output without emacs giving now up and report back if I find anything at all.

**Comment by madsroskar** [comment]
So, the issue with the images, seemingly on my end at least is that the default [here](https://github.com/ahungry/org-jira/blob/01e6a7c17e210dac0608154dd69d637e9733498d/org-jira.el#L640) results in the filename being defaulted to the project ID. If I set `(setq org-jira-property-overrides (list 'filename nil))`, that solves the issue on my end. However, that's just for fetching a single issue, which is what I've trying so far. I'll push a PR about it so there's a bit more context to it. Running `org-jira-get-issues` still freezes on my end though, with "About to render N issues.", so the images alone don't seem to cause is as far as I can tell. (Sorry for the delay, got distracted :) )

**Comment by rand-fu** [comment]
I normally run GUI emacs but I also tested non-gui and I have the same lock up behavior with either.

**Comment by hansffu** [comment]
I've been messing around with this a bit, and found it hanging while using org-element cache (through `org-element-at-point` at least once. I tried calling `org-element-cache-reset` and also deleting the org-jira files, and it seems to work flawlessly for now.

I'm not sure if this is the fix, or I'm just fetching different jira issues, but maybe someone else can give it a try?

I also found this in the log (before cache reset), not sure it's related
```
eieio-oset: Invalid slot type: org-jira-sdk-issue, created, string, nil
```

**Comment by ahungry** [comment]
Interesting, I see this documentation on org-element-use-cache:

```
org-element-use-cache is a variable defined in org-element.el.

Value
nil

Toggle Set

Documentation
Non-nil when Org parser should cache its results.

WARNING: for the time being, using cache sometimes triggers
freezes.  Therefore, it is disabled by default.  Activate it if
you want to help debugging the issue.

```

I've never used it myself, and it is set to nil for me on my Org version - if it is indeed org-element related, the one reference to org-element in the org-jira code could hit an infinite loop (aka max CPU freeze) if it gave incorrect responses, as it is used to go to the top of a page and find the top element header as such:

```lisp
(defun org-jira--is-top-headline? (proj-key)
  "For PROJ-KEY, check if it is a top headline or not."
  (let ((elem (org-element-at-point)))
    (and (eq 'headline (car elem))
         (equal (format "%s-Tickets" proj-key)
                (plist-get (cadr elem) :title))
         (= 1 (plist-get (cadr elem) :level)))))

(defun org-jira--maybe-render-top-heading (proj-key)
  "Ensure that there is a headline for PROJ-KEY at the top of the file."
  (goto-char (point-min))
  (let ((top-heading (format ".*%s-Tickets" proj-key))
        (th-found? nil))
    (while (and (not (eobp))
                (not th-found?))
      (beginning-of-line)
      (when (org-jira--is-top-headline? proj-key) (setq th-found? t))
      (re-search-forward top-heading nil 1 1))
    (beginning-of-line)
    (unless (looking-at top-heading)
      (insert (format "\n* %s-Tickets\n" proj-key)))))
```

So, as you can see, there would be problematic parsing/rendering issues if org-element-at-point didn't work as it does with non-cache mode.

**Comment by ahungry** [comment]
Thanks @hansffu for the find - for everyone else - what's the value of your `org-element-use-cache ` setting?

**Comment by rand-fu** [comment]
@hansffu great find, Ive tested this a few times with different issues, boards, anything that was locking up for me before and it so far seems to work.  I was not able to find the same string you have in the logs before cache reset, at least not yet.  

I didn't explicitly set to use this but  the value of  my `org-element-use-cache` is not nil

```λ (print org-element-use-cache)
t
```
I wonder if that happened during a version bump for me.... I also recently migrated to use roamv2. I'll put this through the ringer next week with work and see if it looks like a fix.

Thanks!

**Comment by AW3i** [comment]
I can confirm that setting the variable `org-element-use-cache` to nil, fixes the lockup and pulls the issues as intended.
I'm at orgmode 9.6 and emacs 27.2

**Comment by ahungry** [comment]
Thanks @AW3i - I guess the next issue to track down is who or what is setting org-element-use-cache to t instead of leaving it as nil, as the doc for it even mentions it'll cause freezing issues and should only be enabled if you're helping the org team debug said freezing issue.

Since this isn't an org-jira problem, I'll go ahead and close the ticket.

**Comment by madsroskar** [comment]
It seems like `org-element-use-cache` is set to `t` from the get-go in [`org-element.el`](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/org-element.el#n5269) as far as I can tell. Could it make sense to mention it in the readme maybe, for people trying to use this package in the future?

**Comment by ahungry** [comment]
Ugh - they made it the default in the package despite the warn message still being present?

Maybe I will have to expand to accommodate the setting, if it isn't some random package toggling it on - perhaps temporarily disabling it in the block that it gets used in org-jira and re-enabling when the block is done running.

**Comment by dustinfarris** [comment]
FYI it looks like they overhauled the cache system in the same commit that changed the default to `t`

https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/lisp/org-element.el?id=fc80d052db3374d04ac29170232326f1eba1aeb6

`org-jira-get-issues` freezes for me as well on a fresh install of doom emacs.

```
GNU Emacs 28.0.50
org-mode 9.6
```

**Comment by dustinfarris** [comment]
If anyone else runs into this, this workaround is working for me:

```Elisp
(advice-add 'org-jira-get-issues :before (lambda (&rest r) (setq org-element-use-cache nil)))
(advice-add 'org-jira-get-issues :after (lambda (&rest r) (setq org-element-use-cache t)))
```

**Comment by ahungry** [comment]
I need to test this out (extra testers welcome) - but this should fix it in a similar way to your defadvice (ty)

https://github.com/ahungry/org-jira/pull/282

**Comment by dustinfarris** [comment]
f424364 fixed it for me!  :-)

**Comment by ahungry** [comment]
Excellent!  Going to close this, but others feel free to comment and we can re-open if there are further issues around this specific problem.

**Comment by rcallagh** [comment]
I'm having this problem using doom emacs 28.1 on macOS 12.4 with org-mode version 9.6. The version of org-jira that doom has installed in at commit c0c0086419b4e68bb45bf609931916d6d8ae48a2

When I try to use `org-jira-get-issues` I get the message `About to render 16 issues` and then it just hangs. I tried adding the advice-add approach from @dustinfarris to my config.el but it didn't make any difference.

**Comment by rcallagh** [comment]
@ahungry Is there any diagnostic can run to figure out what is causing this to hang? I tried to just set `org-element-use-cache` to nil but it still hangs for me.
